kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-sqldata-dev
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 40Mi
  accessModes:
  -  ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/sqlite_data_dev


