apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - ../../base
namespace: django-dev
replicas:
  - name: django-web-app
    count: 1

# The image name and tag will be replaced automatically by GitHub Actions
images:
  - name: ghcr.io/hnijbacker/django-web-app
    newName: ghcr.io/hnijbacker/django-web-app
    newTag: PLACEHOLDER_VERSION

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/environment: dev
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/version: PLACEHOLDER_VERSION
    includeSelectors: false
    includeTemplates: true

commonAnnotations:
  git.sha: PLACEHOLDER_GIT_SHA