name: Build and push deploy image

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: paridaen/django-web-app-deploy

jobs:
   print-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch
        run: echo "Branch/tag is ${GITHUB_REF_NAME}"
      
   build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }} # for pr head_ref is empty so use tag 

      - name: Find branch containing tag commit
        id: find-branch
        run: |
          COMMIT_SHA=$(git rev-list -n 1 "${GITHUB_REF_NAME}")
          echo "Commit SHA: $COMMIT_SHA"

          echo "Remote branches containing commit:"
          git fetch --all --quiet
          BRANCHES=$(git branch -r --contains "$COMMIT_SHA" | sed 's|origin/||' | tr '\n' ' ')
          echo "Branches: $BRANCHES"

          # Pick the first branch (you can change selection logic here)
          MAIN_BRANCH=$(echo "$BRANCHES" | awk '{print $1}')
          echo "Selected branch: $MAIN_BRANCH"

          # Set output for later steps
          echo "branch=$MAIN_BRANCH" >> $GITHUB_OUTPUT

      - name: Show selected branch
        run: |
          echo "Branch for tag is: '${{ steps.find-branch.outputs.branch }}'"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: echo "Tag is ${{ github.ref_name }}" >> $GITHUB_OUTPUT
        
      - name: Setup ORAS
        uses: oras-project/setup-oras@v1

      - name: Use ORAS
        run: oras version

      - name: Package deployment manifests as OCI artifact
        env:
          DEPLOY_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extrac_tag.outputs.tag }}
        run: |
          tar czf deployment.tgz deploy
          oras push "${{ env.DEPLOY_TAG }}" deployment.tgz:application/vnd.oci.image.layer.v1.tar+gzip
