name: One-Click Promote Release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hnijbacker/django-web-app
  IMAGE_NAME_CONFIG: hnijbacker/django-web-app-config

on:
  workflow_dispatch:
    inputs:
      source_env:
        description: 'Source environment (dev)'
        required: true
        default: dev
      target_env:
        description: 'Target environment (prod)'
        required: true
        default: prod
      version:
        description: 'Version to promote (v1.3.0, etc.)'
        required: false

jobs:
  promote:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}  # approval gate for staging/prod
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup ORAS
        uses: oras-project/setup-oras@v1

      - name: Use ORAS
        run: oras version

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: ORAS Login
      #   run: oras login ghcr.io -u ${{ github.actor }} -p {{ secrets.GITHUB_TOKEN }}
          
      - name: Determine version if not provided
        id: version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            # Pull latest version from source environment tag
            VERSION=$(oras manifest inspect ${IMAGE_NAME_CONFIG}:${{ github.event.inputs.source_env }} | jq -r '.config.digest')
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Promote Kustomize OCI bundle
        run: |
          echo "Promoting ${{ steps.version.outputs.VERSION }} → ${{ github.event.inputs.target_env }}"
          oras copy \
            ${REGISTRY}/${IMAGE_NAME_CONFIG}:${{ steps.version.outputs.VERSION }} \
            ${REGISTRY}/${IMAGE_NAME_CONFIG}:${{ github.event.inputs.target_env }}
